/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as GateRouteImport } from './routes/gate'
import { Route as LearnedRouteImport } from './routes/learned'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as NotificationsRouteImport } from './routes/notifications'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GateRoute = GateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnedRoute = LearnedRouteImport.update({
  id: '/learned',
  path: '/learned',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gate': typeof GateRoute
  '/learned': typeof LearnedRoute
  '/ledger': typeof LedgerRoute
  '/notifications': typeof NotificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gate': typeof GateRoute
  '/learned': typeof LearnedRoute
  '/ledger': typeof LedgerRoute
  '/notifications': typeof NotificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gate': typeof GateRoute
  '/learned': typeof LearnedRoute
  '/ledger': typeof LedgerRoute
  '/notifications': typeof NotificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/gate' | '/learned' | '/ledger' | '/notifications'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/gate' | '/learned' | '/ledger' | '/notifications'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/gate'
    | '/learned'
    | '/ledger'
    | '/notifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GateRoute: typeof GateRoute
  LearnedRoute: typeof LearnedRoute
  LedgerRoute: typeof LedgerRoute
  NotificationsRoute: typeof NotificationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate': {
      id: '/gate'
      path: '/gate'
      fullPath: '/gate'
      preLoaderRoute: typeof GateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learned': {
      id: '/learned'
      path: '/learned'
      fullPath: '/learned'
      preLoaderRoute: typeof LearnedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GateRoute: GateRoute,
  LearnedRoute: LearnedRoute,
  LedgerRoute: LedgerRoute,
  NotificationsRoute: NotificationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
