/**
 * Export the verified local database as SQL, for loading into D1.
 *
 * The local SQLite file is the one `verify-recovery.ts` proved correct, so the
 * deployed database is a copy of a checked artifact rather than a second seed
 * run that might drift from it.
 *
 * Blobs are emitted as `X'...'` hex literals, which is the only portable way to
 * carry the posterior's mu and sigma through a text file without losing bits.
 *
 * Usage:  bun run scripts/export-seed.ts > .data/seed.sql
 */

import { Database } from 'bun:sqlite';

const db = new Database(process.argv[2] ?? '.data/dev.db', { readonly: true });

// Order matters: parents before children, so foreign keys resolve as the file
// is replayed top to bottom.
const TABLES = [
  'creators',
  'posts',
  'features',
  'metrics',
  'experiments',
  'baselines',
  'posteriors',
  'posterior_snapshots',
  'belief_diffs',
  'niche_priors',
  'claims',
  'bits',
  'briefs',
  'gate_events',
  'notifications',
];

function literal(v: unknown): string {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  if (typeof v === 'bigint') return String(v);
  if (typeof v === 'boolean') return v ? '1' : '0';
  if (v instanceof Uint8Array || v instanceof ArrayBuffer) {
    const bytes = v instanceof ArrayBuffer ? new Uint8Array(v) : v;
    let hex = '';
    for (const b of bytes) hex += b.toString(16).padStart(2, '0');
    return `X'${hex}'`;
  }
  return `'${String(v).replace(/'/g, "''")}'`;
}

const out: string[] = [];
out.push('-- Generated by scripts/export-seed.ts. Do not edit by hand.');
out.push('-- Source: the local database verified by scripts/verify-recovery.ts.');

let total = 0;
for (const table of TABLES) {
  const rows = db.query(`SELECT * FROM ${table}`).all() as Record<string, unknown>[];
  if (rows.length === 0) continue;
  const cols = Object.keys(rows[0]!);
  out.push(`\n-- ${table}: ${rows.length} rows`);
  for (const row of rows) {
    const values = cols.map((c) => literal(row[c])).join(', ');
    out.push(`INSERT INTO ${table} (${cols.join(', ')}) VALUES (${values});`);
    total++;
  }
}

console.log(out.join('\n'));
console.error(`exported ${total} rows across ${TABLES.length} tables`);
